// 外研社版高中英语（2019版）必修第一册 Words and Expressions

const UNITS = [
  { id: 1, name: "Unit 1 A new start" },
  { id: 2, name: "Unit 2 Exploring English" },
  { id: 3, name: "Unit 3 Family matters" },
  { id: 4, name: "Unit 4 Friends forever" },
  { id: 5, name: "Unit 5 Into the wild" },
  { id: 6, name: "Unit 6 At one with nature" }
];

const WORDS = [
  // ==================== Unit 1: A new start (p.105-106) ====================
  // p.105 左栏
  { id: 1001, word: "senior", meaning: "adj. 级别（或地位）高的", unit: 1 },
  { id: 1002, word: "senior high", meaning: "高中", unit: 1 },
  { id: 1003, word: "curious", meaning: "adj. 好奇的", unit: 1 },
  { id: 1004, word: "impression", meaning: "n. 印象；感想", unit: 1 },
  { id: 1005, word: "campus", meaning: "n. 校园", unit: 1 },
  { id: 1006, word: "tradition", meaning: "n. 传统；惯例", unit: 1 },
  { id: 1007, word: "facility", meaning: "n. 设施；设备", unit: 1 },
  { id: 1008, word: "make an impression", meaning: "留下好印象", unit: 1 },
  { id: 1009, word: "moment", meaning: "n. 片刻；瞬间", unit: 1 },
  { id: 1010, word: "senior", meaning: "n. 高年级学生", unit: 1 },
  { id: 1011, word: "explore", meaning: "v. 探索；考察", unit: 1 },
  { id: 1012, word: "one by one", meaning: "逐一地；一个一个地", unit: 1 },
  { id: 1013, word: "origin", meaning: "n. 起源；起因；由来", unit: 1 },
  { id: 1014, word: "butterfly", meaning: "n. 蝴蝶", unit: 1 },
  { id: 1015, word: "have butterflies in one's stomach", meaning: "心里七上八下；紧张", unit: 1 },
  { id: 1016, word: "breathe", meaning: "v. 呼吸", unit: 1 },
  // p.105 右栏
  { id: 1017, word: "in pairs", meaning: "结对地", unit: 1 },
  { id: 1018, word: "challenge", meaning: "n. 挑战", unit: 1 },
  { id: 1019, word: "pressure", meaning: "n. 压力", unit: 1 },
  { id: 1020, word: "calm", meaning: "adj. 镇静的；沉着的", unit: 1 },
  { id: 1021, word: "calm down", meaning: "（使）平静；（使）镇静", unit: 1 },
  { id: 1022, word: "disease", meaning: "n. 疾病", unit: 1 },
  { id: 1023, word: "confident", meaning: "adj. 自信的；有把握的", unit: 1 },
  { id: 1024, word: "power", meaning: "n. 能力", unit: 1 },
  { id: 1025, word: "junior", meaning: "adj. 低年级的 n. 低年级学生", unit: 1 },
  { id: 1026, word: "goal", meaning: "n. 目标；目的", unit: 1 },
  { id: 1027, word: "look forward to", meaning: "盼望；期待", unit: 1 },
  { id: 1028, word: "chemistry", meaning: "n. 化学", unit: 1 },
  { id: 1029, word: "photographer", meaning: "n. 摄影师", unit: 1 },
  { id: 1030, word: "concentrate", meaning: "v. 集中（注意力）", unit: 1 },
  { id: 1031, word: "experiment", meaning: "n. 实验", unit: 1 },
  { id: 1032, word: "awkward", meaning: "adj. 令人尴尬的", unit: 1 },
  { id: 1033, word: "teenager", meaning: "n. 青少年", unit: 1 },
  { id: 1034, word: "donate", meaning: "v. 捐赠；捐献", unit: 1 },
  { id: 1035, word: "intelligence", meaning: "n. 智力；聪明", unit: 1 },
  { id: 1036, word: "investigate", meaning: "v. 调查；研究", unit: 1 },
  // p.106 左栏 (Unit 1 继续)
  { id: 1037, word: "various", meaning: "adj. 各种各样的；各种不同的", unit: 1 },
  { id: 1038, word: "volunteer", meaning: "n. 志愿者 v. 义务做", unit: 1 },
  { id: 1039, word: "立志做...", meaning: "立志做...", unit: 1 },
  { id: 1040, word: "apply", meaning: "v. 申请", unit: 1 },
  { id: 1041, word: "apply for", meaning: "申请", unit: 1 },
  { id: 1042, word: "schedule", meaning: "n. 日程表；计划表", unit: 1 },
  { id: 1043, word: "award", meaning: "n. 奖；奖项", unit: 1 },
  { id: 1044, word: "representative", meaning: "n. 代表", unit: 1 },
  { id: 1045, word: "take on", meaning: "承担", unit: 1 },
  { id: 1046, word: "subscribe", meaning: "v. 订阅", unit: 1 },
  { id: 1047, word: "view", meaning: "n. 看法；见解", unit: 1 },
  { id: 1048, word: "former", meaning: "adj. 以前的", unit: 1 },
  { id: 1049, word: "undergraduate", meaning: "n. 本科生", unit: 1 },
  { id: 1050, word: "职业规划/在职培训", meaning: "职业规划/在职培训", unit: 1 },
  { id: 1051, word: "Orientation Day", meaning: "迎新日", unit: 1 },
  { id: 1052, word: "frightened", meaning: "adj. 害怕的；惊吓的", unit: 1 },
  { id: 1053, word: "right away", meaning: "立刻；马上", unit: 1 },
  { id: 1054, word: "sight", meaning: "n. 视力；视觉", unit: 1 },
  { id: 1055, word: "go all out", meaning: "全力以赴；竭尽全力", unit: 1 },
  { id: 1056, word: "select", meaning: "v. 挑选；选择", unit: 1 },
  { id: 1057, word: "take a deep breath", meaning: "深呼吸", unit: 1 },
  { id: 1058, word: "rainbow", meaning: "n. 彩虹", unit: 1 },
  { id: 1059, word: "neat", meaning: "adj. 整洁的；井然有序的", unit: 1 },
  { id: 1060, word: "sparkle", meaning: "v. 闪烁", unit: 1 },
  { id: 1061, word: "anxious", meaning: "adj. 焦虑的；不安的", unit: 1 },
  // p.106 右栏 (Unit 1 继续)
  { id: 1062, word: "refer to", meaning: "指的是；描述；涉及", unit: 1 },
  { id: 1063, word: "junior", meaning: "n. 低年级学生", unit: 1 },
  { id: 1064, word: "struggle", meaning: "v. 奋斗；努力", unit: 1 },
  { id: 1065, word: "forward", meaning: "adv. 向前", unit: 1 },
  { id: 1066, word: "misunderstanding", meaning: "n. 误解；误会", unit: 1 },
  { id: 1067, word: "improve", meaning: "v. 改进；改善", unit: 1 },
  { id: 1068, word: "look back on", meaning: "回顾；回首", unit: 1 },
  { id: 1069, word: "real", meaning: "n. 一件事，作为", unit: 1 },
  { id: 1070, word: "performance", meaning: "n. 表演；表现", unit: 1 },
  { id: 1071, word: "exchange", meaning: "n. 交换；交流", unit: 1 },
  { id: 1072, word: "新生结对帮助", meaning: "新生结对帮助", unit: 1 },
  { id: 1073, word: "annoyed", meaning: "adj. 恼怒的；生气的", unit: 1 },
  { id: 1074, word: "information", meaning: "n. 信息；消息", unit: 1 },
  { id: 1075, word: "run for", meaning: "竞选", unit: 1 },
  { id: 1076, word: "position", meaning: "n. 职位；位置", unit: 1 },
  { id: 1077, word: "sign up for", meaning: "报名参加", unit: 1 },
  { id: 1078, word: "extra-curricular", meaning: "adj. 课外的", unit: 1 },
  { id: 1079, word: "be responsible for", meaning: "对……负责", unit: 1 },
  { id: 1080, word: "quit", meaning: "v. 停止；戒掉；离开", unit: 1 },
  { id: 1081, word: "lecture", meaning: "n. 讲座；演讲", unit: 1 },
  { id: 1082, word: "partner", meaning: "n. 搭档；同伴", unit: 1 },
  { id: 1083, word: "confident", meaning: "n. 知心朋友", unit: 1 },
  { id: 1084, word: "opportunity", meaning: "n. 机会；时机", unit: 1 },
  { id: 1085, word: "organisation", meaning: "n. 组织；机构", unit: 1 },
  { id: 1086, word: "organise", meaning: "v. 组织；筹划", unit: 1 },
  { id: 1087, word: "make the most of", meaning: "充分利用", unit: 1 },
  { id: 1088, word: "on one's own", meaning: "独自；独立地", unit: 1 },
  { id: 1089, word: "confidence", meaning: "n. 信心；自信", unit: 1 },
  { id: 1090, word: "description", meaning: "n. 描述；形容", unit: 1 },
  { id: 1091, word: "behaviour", meaning: "n. 行为；举止", unit: 1 },
  { id: 1092, word: "curious about", meaning: "对……好奇", unit: 1 },
  { id: 1093, word: "anxious about", meaning: "对……焦虑", unit: 1 },
  { id: 1094, word: "annoyed with", meaning: "对……生气", unit: 1 },
  { id: 1095, word: "frightened of", meaning: "害怕……", unit: 1 },
  { id: 1096, word: "confident about", meaning: "对……有信心", unit: 1 },
  { id: 1097, word: "what if", meaning: "要是……会怎么样呢", unit: 1 },

  // ==================== Unit 2: Exploring English (p.106-108) ====================
  { id: 2001, word: "bite", meaning: "v. 咬", unit: 2 },
  { id: 2002, word: "figure", meaning: "n. 数字；人物", unit: 2 },
  { id: 2003, word: "eggplant", meaning: "n. 茄子", unit: 2 },
  { id: 2004, word: "pose", meaning: "v. 造成；引起", unit: 2 },
  { id: 2005, word: "pineapple", meaning: "n. 菠萝", unit: 2 },
  { id: 2006, word: "homesick", meaning: "adj. 想家的", unit: 2 },
  { id: 2007, word: "upsetting", meaning: "adj. 令人不安的；令人心烦的", unit: 2 },
  { id: 2008, word: "behaviour", meaning: "n. 举止；行为", unit: 2 },
  { id: 2009, word: "confusing", meaning: "adj. 令人困惑的", unit: 2 },
  { id: 2010, word: "capitalised", meaning: "adj. 大写的", unit: 2 },
  { id: 2011, word: "burn up", meaning: "烧毁；烧尽", unit: 2 },
  { id: 2012, word: "idiom", meaning: "n. 习语；成语", unit: 2 },
  { id: 2013, word: "alarm", meaning: "n. 警报；闹钟", unit: 2 },
  { id: 2014, word: "reflect", meaning: "v. 反映；反射", unit: 2 },
  { id: 2015, word: "cautiously", meaning: "adv. 小心地；谨慎地", unit: 2 },
  { id: 2016, word: "valid", meaning: "adj. 有效的", unit: 2 },
  { id: 2017, word: "creature", meaning: "n. 生物", unit: 2 },
  { id: 2018, word: "type", meaning: "n. 类型；种类", unit: 2 },
  { id: 2019, word: "unfortunate", meaning: "adj. 不幸的", unit: 2 },
  { id: 2020, word: "contract", meaning: "n. 合同；契约", unit: 2 },
  { id: 2021, word: "organisation", meaning: "n. 组织；机构", unit: 2 },
  { id: 2022, word: "likely", meaning: "adj. 可能的", unit: 2 },
  { id: 2023, word: "subway", meaning: "n. 地铁", unit: 2 },
  { id: 2024, word: "highway", meaning: "n. 公路", unit: 2 },
  { id: 2025, word: "give", meaning: "n. 弹性", unit: 2 },
  { id: 2026, word: "period", meaning: "n. 时期；阶段", unit: 2 },
  { id: 2027, word: "apartment", meaning: "n. 公寓", unit: 2 },
  { id: 2028, word: "comment", meaning: "n./v. 评论；议论", unit: 2 },
  { id: 2029, word: "unique", meaning: "adj. 独一无二的", unit: 2 },
  { id: 2030, word: "addition", meaning: "n. 增加；添加", unit: 2 },
  { id: 2031, word: "in addition (to)", meaning: "除……之外（还）", unit: 2 },
  { id: 2032, word: "phrase", meaning: "n. 短语；词组", unit: 2 },
  { id: 2033, word: "version", meaning: "n. 版本", unit: 2 },
  { id: 2034, word: "misunderstand", meaning: "v. 误解；误会", unit: 2 },
  { id: 2035, word: "method", meaning: "n. 方法", unit: 2 },
  { id: 2036, word: "rather", meaning: "adv. 相当；宁可", unit: 2 },
  { id: 2037, word: "have a frog in one's throat", meaning: "（因紧张等）声音沙哑", unit: 2 },
  { id: 2038, word: "context", meaning: "n. 上下文；语境", unit: 2 },
  { id: 2039, word: "have butterflies in one's stomach", meaning: "紧张", unit: 2 },
  { id: 2040, word: "boost", meaning: "v. 促进；增强", unit: 2 },
  { id: 2041, word: "head", meaning: "n. 头脑；才能", unit: 2 },
  { id: 2042, word: "informal", meaning: "adj. 非正式的", unit: 2 },
  { id: 2043, word: "audience", meaning: "n. 观众；听众", unit: 2 },
  { id: 2044, word: "odd", meaning: "adj. 奇怪的；古怪的", unit: 2 },
  { id: 2045, word: "recognise", meaning: "v. 认出；承认", unit: 2 },
  { id: 2046, word: "base", meaning: "n. 基础 v. 以……为基础", unit: 2 },
  { id: 2047, word: "be aware of", meaning: "知道；意识到", unit: 2 },
  { id: 2048, word: "talent", meaning: "n. 天赋；才能", unit: 2 },
  { id: 2049, word: "opinion", meaning: "n. 意见；看法", unit: 2 },
  { id: 2050, word: "generation", meaning: "n. 一代人", unit: 2 },
  { id: 2051, word: "gap", meaning: "n. 差距；隔阂", unit: 2 },
  { id: 2052, word: "responsible", meaning: "adj. 有责任的", unit: 2 },
  { id: 2053, word: "pattern", meaning: "n. 模式；图案", unit: 2 },
  { id: 2054, word: "desperately", meaning: "adv. 拼命地；绝望地", unit: 2 },
  { id: 2055, word: "billion", meaning: "num. 十亿", unit: 2 },
  { id: 2056, word: "native", meaning: "adj. 出生地的；本土的", unit: 2 },
  { id: 2057, word: "speaker", meaning: "n. 说某种语言的人", unit: 2 },
  { id: 2058, word: "attitude", meaning: "n. 态度；看法", unit: 2 },
  { id: 2059, word: "refer", meaning: "v. 提到；谈到", unit: 2 },
  { id: 2060, word: "refer to", meaning: "指的是；描述", unit: 2 },
  { id: 2061, word: "refer to...as", meaning: "把……称作", unit: 2 },
  { id: 2062, word: "system", meaning: "n. 系统；体系", unit: 2 },
  { id: 2063, word: "despite", meaning: "prep. 尽管；虽然", unit: 2 },
  { id: 2064, word: "factor", meaning: "n. 因素", unit: 2 },
  { id: 2065, word: "be based on", meaning: "以……为基础", unit: 2 },
  { id: 2066, word: "equal", meaning: "adj. 相同的；同样的", unit: 2 },
  { id: 2067, word: "global", meaning: "adj. 全球的；全世界的", unit: 2 },
  { id: 2068, word: "demand", meaning: "n. 需求；要求", unit: 2 },
  { id: 2069, word: "vocabulary", meaning: "n. 词汇；词汇量", unit: 2 },
  { id: 2070, word: "lack", meaning: "v./n. 缺乏；没有", unit: 2 },
  { id: 2071, word: "accent", meaning: "n. 口音；腔调", unit: 2 },
  { id: 2072, word: "the number of", meaning: "……的数量", unit: 2 },
  { id: 2073, word: "a number of", meaning: "若干；许多", unit: 2 },
  { id: 2074, word: "variety", meaning: "n. 多样化；变化；种类", unit: 2 },
  { id: 2075, word: "a variety of", meaning: "各种各样的", unit: 2 },
  { id: 2076, word: "differ", meaning: "v. 相异；不同于", unit: 2 },
  { id: 2077, word: "differ from", meaning: "和……不同", unit: 2 },
  { id: 2078, word: "play a...role", meaning: "起……作用", unit: 2 },
  { id: 2079, word: "actually", meaning: "adv. 事实上；的确", unit: 2 },
  { id: 2080, word: "expression", meaning: "n. 表达；表情", unit: 2 },
  { id: 2081, word: "command", meaning: "n. 命令；掌握", unit: 2 },
  { id: 2082, word: "request", meaning: "n. 要求；请求", unit: 2 },
  { id: 2083, word: "direction", meaning: "n. 方向", unit: 2 },
  { id: 2084, word: "politely", meaning: "adv. 礼貌地", unit: 2 },
  { id: 2085, word: "straight", meaning: "adv. 直接；径直", unit: 2 },
  { id: 2086, word: "go straight on", meaning: "一直走", unit: 2 },
  { id: 2087, word: "block", meaning: "n. 街区", unit: 2 },
  { id: 2088, word: "process", meaning: "n. 进程；过程", unit: 2 },
  { id: 2089, word: "consist", meaning: "v. 由……组成", unit: 2 },
  { id: 2090, word: "consist of", meaning: "由……组成", unit: 2 },
  { id: 2091, word: "borrow", meaning: "v. 借；借用", unit: 2 },
  { id: 2092, word: "borrow from", meaning: "向……借", unit: 2 },
  { id: 2093, word: "official", meaning: "adj. 官方的；正式的", unit: 2 },
  { id: 2094, word: "voyage", meaning: "n. 航海；航行", unit: 2 },
  { id: 2095, word: "gradually", meaning: "adv. 逐渐地", unit: 2 },
  { id: 2096, word: "identity", meaning: "n. 特征；身份", unit: 2 },
  { id: 2097, word: "spelling", meaning: "n. 拼写", unit: 2 },
  { id: 2098, word: "distinguish", meaning: "v. 区分；辨别", unit: 2 },
  { id: 2099, word: "ban", meaning: "v. 禁止；取缔", unit: 2 },
  { id: 2100, word: "put forward", meaning: "提出（观点、议案等）", unit: 2 },

  // ==================== Unit 3: Family matters (p.108-109) ====================
  { id: 3001, word: "character", meaning: "n. （书、剧本、电影等中的）人物；角色", unit: 3 },
  { id: 3002, word: "approach", meaning: "v. 走近；靠近 n. 方法", unit: 3 },
  { id: 3003, word: "chat", meaning: "v./n. 聊天；闲谈", unit: 3 },
  { id: 3004, word: "focus", meaning: "v. 集中 n. 焦点", unit: 3 },
  { id: 3005, word: "focus on", meaning: "集中于；关注", unit: 3 },
  { id: 3006, word: "measure", meaning: "n. 措施 v. 测量", unit: 3 },
  { id: 3007, word: "lawyer", meaning: "n. 律师", unit: 3 },
  { id: 3008, word: "expect", meaning: "v. 预料；期待", unit: 3 },
  { id: 3009, word: "court", meaning: "n. 法庭；球场", unit: 3 },
  { id: 3010, word: "professional", meaning: "adj. 专业的 n. 专业人员", unit: 3 },
  { id: 3011, word: "judge", meaning: "n. 法官；裁判 v. 判断", unit: 3 },
  { id: 3012, word: "white lie", meaning: "善意的谎言", unit: 3 },
  { id: 3013, word: "feature", meaning: "n. 特点；特征", unit: 3 },
  { id: 3014, word: "typically", meaning: "adv. 典型地；通常", unit: 3 },
  { id: 3015, word: "individual", meaning: "adj. 个人的 n. 个人", unit: 3 },
  { id: 3016, word: "style", meaning: "n. 风格；方式", unit: 3 },
  { id: 3017, word: "extra", meaning: "adj. 额外的", unit: 3 },
  { id: 3018, word: "detail", meaning: "n. 细节；详情", unit: 3 },
  { id: 3019, word: "summary", meaning: "n. 总结；摘要", unit: 3 },
  { id: 3020, word: "powerful", meaning: "adj. 强有力的", unit: 3 },
  { id: 3021, word: "review", meaning: "n./v. 评论；复习", unit: 3 },
  { id: 3022, word: "in the lead", meaning: "领先；处于首位", unit: 3 },
  { id: 3023, word: "come", meaning: "v. 变成；变得", unit: 3 },
  { id: 3024, word: "event", meaning: "n. 事件；活动", unit: 3 },
  { id: 3025, word: "apologise", meaning: "v. 道歉", unit: 3 },
  { id: 3026, word: "strength", meaning: "n. 力量；优势", unit: 3 },
  { id: 3027, word: "admire", meaning: "v. 钦佩；欣赏", unit: 3 },
  { id: 3028, word: "media", meaning: "n. 媒体", unit: 3 },
  { id: 3029, word: "obviously", meaning: "adv. 明显地", unit: 3 },
  { id: 3030, word: "despite", meaning: "prep. 尽管；虽然", unit: 3 },
  { id: 3031, word: "throughout", meaning: "prep. 贯穿；遍及", unit: 3 },
  { id: 3032, word: "contain", meaning: "v. 包含；容纳", unit: 3 },
  { id: 3033, word: "extremely", meaning: "adv. 极其；非常", unit: 3 },
  { id: 3034, word: "pattern", meaning: "n. 模式；图案", unit: 3 },
  { id: 3035, word: "indeed", meaning: "adv. 的确；确实", unit: 3 },
  { id: 3036, word: "familiar", meaning: "adj. 熟悉的", unit: 3 },
  { id: 3037, word: "favourite", meaning: "adj. 最喜欢的 n. 最喜欢的人或物", unit: 3 },
  { id: 3038, word: "prefer", meaning: "v. 更喜欢；宁愿", unit: 3 },
  { id: 3039, word: "lose track of", meaning: "不了解……的情况；与……失去联系", unit: 3 },
  { id: 3040, word: "teenager", meaning: "n. 青少年", unit: 3 },
  { id: 3041, word: "adult", meaning: "n. 成年人", unit: 3 },
  { id: 3042, word: "argument", meaning: "n. 争吵；争论", unit: 3 },
  { id: 3043, word: "calm", meaning: "adj. 镇静的；沉着的", unit: 3 },
  { id: 3044, word: "calm down", meaning: "（使）平静下来", unit: 3 },
  { id: 3045, word: "ignore", meaning: "v. 忽视；不理睬", unit: 3 },
  { id: 3046, word: "gap", meaning: "n. 差距；隔阂", unit: 3 },
  { id: 3047, word: "generation", meaning: "n. 一代人；一代", unit: 3 },
  { id: 3048, word: "generation gap", meaning: "代沟", unit: 3 },
  { id: 3049, word: "respect", meaning: "v./n. 尊敬；尊重", unit: 3 },
  { id: 3050, word: "trust", meaning: "v./n. 信任；信赖", unit: 3 },
  { id: 3051, word: "in return", meaning: "作为回报", unit: 3 },
  { id: 3052, word: "open up", meaning: "敞开心扉；畅所欲言", unit: 3 },
  { id: 3053, word: "concern", meaning: "n./v. 担心；担忧", unit: 3 },
  { id: 3054, word: "be concerned about", meaning: "对……担忧/关心", unit: 3 },
  { id: 3055, word: "communicate", meaning: "v. 交流；沟通", unit: 3 },
  { id: 3056, word: "support", meaning: "v./n. 支持", unit: 3 },
  { id: 3057, word: "grateful", meaning: "adj. 感激的；表示感谢的", unit: 3 },
  { id: 3058, word: "think of...as", meaning: "把……看作", unit: 3 },
  { id: 3059, word: "suggest", meaning: "v. 建议；提议", unit: 3 },
  { id: 3060, word: "suppose", meaning: "v. 猜想；假设；料想", unit: 3 },
  { id: 3061, word: "be supposed to", meaning: "应该；应当", unit: 3 },
  { id: 3062, word: "fault", meaning: "n. 错误；过失", unit: 3 },
  { id: 3063, word: "responsible", meaning: "adj. 有责任的；负责的", unit: 3 },
  { id: 3064, word: "selfish", meaning: "adj. 自私的", unit: 3 },
  { id: 3065, word: "gentle", meaning: "adj. 和善的；温和的", unit: 3 },
  { id: 3066, word: "strict", meaning: "adj. 严格的；严厉的", unit: 3 },
  { id: 3067, word: "be strict with sb", meaning: "对某人严格", unit: 3 },
  { id: 3068, word: "relationship", meaning: "n. 关系；联系", unit: 3 },
  { id: 3069, word: "distance", meaning: "n. 距离", unit: 3 },
  { id: 3070, word: "skin", meaning: "n. 皮肤", unit: 3 },
  { id: 3071, word: "context", meaning: "n. 上下文；背景", unit: 3 },
  { id: 3072, word: "tone", meaning: "n. 语气；口吻", unit: 3 },
  { id: 3073, word: "e-book", meaning: "n. 电子书", unit: 3 },
  { id: 3074, word: "function", meaning: "n. 功能", unit: 3 },
  { id: 3075, word: "there", meaning: "n. 那里；那个地方", unit: 3 },
  { id: 3076, word: "theme", meaning: "n. 主题", unit: 3 },

  // ==================== Unit 4: Friends forever (p.109-111) ====================
  { id: 4001, word: "quality", meaning: "n. 品德；素质", unit: 4 },
  { id: 4002, word: "fond", meaning: "adj. 喜爱", unit: 4 },
  { id: 4003, word: "be fond of", meaning: "喜欢；喜爱", unit: 4 },
  { id: 4004, word: "loyal", meaning: "adj. 忠诚的；忠实的", unit: 4 },
  { id: 4005, word: "in need", meaning: "在困难时；在危难中", unit: 4 },
  { id: 4006, word: "forever", meaning: "adv. 永远", unit: 4 },
  { id: 4007, word: "adventure", meaning: "n. 冒险（经历）；奇遇", unit: 4 },
  { id: 4008, word: "prove", meaning: "v. 证明是；结果是", unit: 4 },
  { id: 4009, word: "count on", meaning: "依赖；依靠", unit: 4 },
  { id: 4010, word: "make friends with", meaning: "和……交朋友", unit: 4 },
  { id: 4011, word: "from then on", meaning: "从那时起", unit: 4 },
  { id: 4012, word: "inspire", meaning: "v. 激励；鼓舞", unit: 4 },
  { id: 4013, word: "share...with", meaning: "与……分享", unit: 4 },
  { id: 4014, word: "virtue", meaning: "n. 美德；优秀品质", unit: 4 },
  { id: 4015, word: "precious", meaning: "adj. 珍贵的；宝贵的", unit: 4 },
  { id: 4016, word: "through thick and thin", meaning: "同甘共苦；不畏艰险", unit: 4 },
  { id: 4017, word: "familiar", meaning: "adj. 熟悉的", unit: 4 },
  { id: 4018, word: "be familiar with", meaning: "对……熟悉", unit: 4 },
  { id: 4019, word: "bond", meaning: "n. 纽带；联系", unit: 4 },
  { id: 4020, word: "keep in touch with", meaning: "与……保持联系", unit: 4 },
  { id: 4021, word: "turn to", meaning: "向……求助", unit: 4 },
  { id: 4022, word: "generous", meaning: "adj. 慷慨的；大方的", unit: 4 },
  { id: 4023, word: "a couple of", meaning: "两三个；几个", unit: 4 },
  { id: 4024, word: "honour", meaning: "v. 尊敬；给……荣誉", unit: 4 },
  { id: 4025, word: "sacrifice", meaning: "n./v. 牺牲", unit: 4 },
  { id: 4026, word: "embrace", meaning: "v. 拥抱；欣然接受", unit: 4 },
  { id: 4027, word: "outstanding", meaning: "adj. 杰出的；优秀的", unit: 4 },
  { id: 4028, word: "extraordinary", meaning: "adj. 不一般的；非凡的", unit: 4 },
  { id: 4029, word: "devote", meaning: "v. 致力于；献身于", unit: 4 },
  { id: 4030, word: "devote oneself to", meaning: "致力于；献身于", unit: 4 },
  { id: 4031, word: "decade", meaning: "n. 十年", unit: 4 },
  { id: 4032, word: "cooperate", meaning: "v. 合作；配合", unit: 4 },
  { id: 4033, word: "as a result", meaning: "结果", unit: 4 },
  { id: 4034, word: "companion", meaning: "n. 伙伴；同伴", unit: 4 },
  { id: 4035, word: "resolve", meaning: "v. 解决", unit: 4 },
  { id: 4036, word: "advance", meaning: "v. 进步；前进 n. 进展", unit: 4 },
  { id: 4037, word: "significantly", meaning: "adv. 显著地；重大地", unit: 4 },
  { id: 4038, word: "aim high", meaning: "志存高远", unit: 4 },
  { id: 4039, word: "worldwide", meaning: "adj. 世界范围的；全世界的", unit: 4 },
  { id: 4040, word: "maintain", meaning: "v. 维持；保持", unit: 4 },
  { id: 4041, word: "do it/run hot", meaning: "尽全力做某事/竭尽全力", unit: 4 },
  { id: 4042, word: "dignified", meaning: "adj. 有尊严的；庄重的", unit: 4 },
  { id: 4043, word: "click", meaning: "n./v. 点击；咔嗒声", unit: 4 },
  { id: 4044, word: "annoyed", meaning: "adj. 恼怒的；烦恼的", unit: 4 },
  { id: 4045, word: "aim", meaning: "v./n. 瞄准；目标", unit: 4 },
  { id: 4046, word: "world-level", meaning: "adj. 世界级的", unit: 4 },
  { id: 4047, word: "swing", meaning: "v. 摇摆；挥动", unit: 4 },
  { id: 4048, word: "enormous", meaning: "adj. 巨大的；庞大的", unit: 4 },
  { id: 4049, word: "acquire", meaning: "v. 获得；取得", unit: 4 },
  { id: 4050, word: "goods", meaning: "n. 商品；货物", unit: 4 },
  { id: 4051, word: "lower", meaning: "v. 降低；放低", unit: 4 },
  { id: 4052, word: "disappointing", meaning: "adj. 令人失望的", unit: 4 },
  { id: 4053, word: "inspiring", meaning: "adj. 鼓舞人心的", unit: 4 },
  { id: 4054, word: "pron", meaning: "n. 代词", unit: 4 },
  { id: 4055, word: "per", meaning: "prep. 每；每一", unit: 4 },
  { id: 4056, word: "greet", meaning: "v. 问候；迎接", unit: 4 },
  { id: 4057, word: "comfort", meaning: "v./n. 安慰；舒适", unit: 4 },
  { id: 4058, word: "particular", meaning: "adj. 特别的；特定的", unit: 4 },
  { id: 4059, word: "postpone", meaning: "v. 推迟；延期", unit: 4 },
  { id: 4060, word: "throw the baby out with the bathwater", meaning: "把婴儿和洗澡水一起倒掉（因小失大）", unit: 4 },
  { id: 4061, word: "cheer", meaning: "v. 欢呼；使高兴", unit: 4 },
  { id: 4062, word: "close", meaning: "v./adj. 关闭；亲密的", unit: 4 },
  { id: 4063, word: "make one's fortune", meaning: "发财；致富", unit: 4 },
  { id: 4064, word: "drag", meaning: "v. 拖；拉", unit: 4 },
  { id: 4065, word: "proposition", meaning: "n. 命题；主张", unit: 4 },
  { id: 4066, word: "hostile", meaning: "adj. 敌对的；不友好的", unit: 4 },
  { id: 4067, word: "stomach", meaning: "n. 胃；肚子", unit: 4 },
  { id: 4068, word: "partner", meaning: "n. 搭档；伙伴", unit: 4 },
  { id: 4069, word: "turn up", meaning: "出现；调大", unit: 4 },
  { id: 4070, word: "excerpt", meaning: "n. 摘录；节选", unit: 4 },
  { id: 4071, word: "appointed", meaning: "adj. 约定的；指定的", unit: 4 },
  { id: 4072, word: "strike", meaning: "v. 敲击；打动", unit: 4 },
  { id: 4073, word: "origin", meaning: "n. 起源；出身", unit: 4 },
  { id: 4074, word: "plain", meaning: "adj. 朴素的；明显的", unit: 4 },
  { id: 4075, word: "scene", meaning: "n. 场景；场面", unit: 4 },
  { id: 4076, word: "butterfly", meaning: "n. 蝴蝶", unit: 4 },
  { id: 4077, word: "ashamed", meaning: "adj. 羞愧的；惭愧的", unit: 4 },
  { id: 4078, word: "unfold", meaning: "v. 展开；打开", unit: 4 },
  { id: 4079, word: "location", meaning: "n. 位置；地点", unit: 4 },
  { id: 4080, word: "surroundings", meaning: "n. 周围环境", unit: 4 },
  { id: 4081, word: "personality", meaning: "n. 个性；性格", unit: 4 },
  { id: 4082, word: "atmosphere", meaning: "n. 气氛；大气层", unit: 4 },
  { id: 4083, word: "annual", meaning: "adj. 每年的；年度的", unit: 4 },
  { id: 4084, word: "migration", meaning: "n. 迁徙；移居", unit: 4 },
  { id: 4085, word: "major", meaning: "adj. 主要的；重大的", unit: 4 },
  { id: 4086, word: "take into", meaning: "考虑；纳入", unit: 4 },
  { id: 4087, word: "measure", meaning: "n./v. 措施；测量", unit: 4 },
  { id: 4088, word: "position", meaning: "n. 位置；职位", unit: 4 },
  { id: 4089, word: "amazing", meaning: "adj. 令人惊异的", unit: 4 },
  { id: 4090, word: "chemical", meaning: "adj./n. 化学的；化学物质", unit: 4 },
  { id: 4091, word: "caterpillar", meaning: "n. 毛毛虫", unit: 4 },
  { id: 4092, word: "creature", meaning: "n. 生物；动物", unit: 4 },
  { id: 4093, word: "survive", meaning: "v. 幸存；生存", unit: 4 },
  { id: 4094, word: "accommodation", meaning: "n. 住宿；膳宿", unit: 4 },
  { id: 4095, word: "allow", meaning: "v. 允许；准许", unit: 4 },
  { id: 4096, word: "deal with one issue at one time", meaning: "一次处理一个问题", unit: 4 },

  // ==================== Unit 5: Into the wild (p.111-113) ====================
  { id: 5001, word: "charity", meaning: "n. 慈善；慈善机构", unit: 5 },
  { id: 5002, word: "monarch", meaning: "n. 君主；帝王", unit: 5 },
  { id: 5003, word: "monarch butterfly", meaning: "帝王蝶；黑脉金斑蝶", unit: 5 },
  { id: 5004, word: "Atlantic", meaning: "adj. 大西洋的", unit: 5 },
  { id: 5005, word: "whale", meaning: "n. 鲸", unit: 5 },
  { id: 5006, word: "when the cat's away (the mice will play)", meaning: "山中无老虎，猴子称大王", unit: 5 },
  { id: 5007, word: "鱼头九丸", meaning: "（成语）比喻关键人物或领袖", unit: 5 },
  { id: 5008, word: "hold your horses", meaning: "别着急；稍安勿躁", unit: 5 },
  { id: 5009, word: "once and drop", meaning: "一次性下降", unit: 5 },
  { id: 5010, word: "authority", meaning: "n. 权威；当局", unit: 5 },
  { id: 5011, word: "source", meaning: "n. 来源；源头", unit: 5 },
  { id: 5012, word: "hoard", meaning: "v. 囤积；贮藏", unit: 5 },
  { id: 5013, word: "hesitate", meaning: "v. 犹豫；迟疑", unit: 5 },
  { id: 5014, word: "recover", meaning: "v. 恢复；康复", unit: 5 },
  { id: 5015, word: "shock", meaning: "n./v. 震惊；使震惊", unit: 5 },
  { id: 5016, word: "element", meaning: "n. 元素；要素", unit: 5 },
  { id: 5017, word: "brave the elements", meaning: "不畏恶劣天气", unit: 5 },
  { id: 5018, word: "variety", meaning: "n. 多样性；种类", unit: 5 },
  { id: 5019, word: "per (ad prep.)", meaning: "prep. 每；每一", unit: 5 },
  { id: 5020, word: "concentrate", meaning: "v. 集中；专心", unit: 5 },
  { id: 5021, word: "significant", meaning: "adj. 重要的；有意义的", unit: 5 },
  { id: 5022, word: "dozen", meaning: "n. 一打；十二个", unit: 5 },
  { id: 5023, word: "flood", meaning: "n./v. 洪水；淹没", unit: 5 },
  { id: 5024, word: "capture", meaning: "v. 捕获；俘获", unit: 5 },
  { id: 5025, word: "image", meaning: "n. 图像；形象", unit: 5 },
  { id: 5026, word: "refer all", meaning: "参考全部；涉及所有", unit: 5 },
  { id: 5027, word: "reaction", meaning: "n. 反应", unit: 5 },
  { id: 5028, word: "die out", meaning: "灭绝；消失", unit: 5 },
  { id: 5029, word: "wrap", meaning: "v. 包裹；缠绕", unit: 5 },
  { id: 5030, word: "frost", meaning: "n. 霜；霜冻", unit: 5 },
  { id: 5031, word: "severe", meaning: "adj. 严重的；严峻的", unit: 5 },
  { id: 5032, word: "threaten", meaning: "v. 威胁；恐吓", unit: 5 },
  { id: 5033, word: "therefore", meaning: "adv. 因此；所以", unit: 5 },
  { id: 5034, word: "steep", meaning: "adj. 陡峭的", unit: 5 },
  { id: 5035, word: "preserve", meaning: "v. 保护；保存", unit: 5 },
  { id: 5036, word: "harmony", meaning: "n. 和谐；融洽", unit: 5 },
  { id: 5037, word: "horn", meaning: "n. 角；喇叭", unit: 5 },
  { id: 5038, word: "alarm", meaning: "n. 警报；闹钟", unit: 5 },
  { id: 5039, word: "spot", meaning: "v. 发现；认出 n. 地点", unit: 5 },
  { id: 5040, word: "material", meaning: "n. 材料；物质", unit: 5 },
  { id: 5041, word: "mineral", meaning: "n. 矿物；矿物质", unit: 5 },
  { id: 5042, word: "consumer", meaning: "n. 消费者", unit: 5 },
  { id: 5043, word: "priority", meaning: "n. 优先事项；优先权", unit: 5 },
  { id: 5044, word: "beauty", meaning: "n. 美丽；美人", unit: 5 },
  { id: 5045, word: "barrier", meaning: "n. 障碍；屏障", unit: 5 },
  { id: 5046, word: "emotional", meaning: "adj. 情感的；激动的", unit: 5 },
  { id: 5047, word: "living", meaning: "adj. 活的；现存的", unit: 5 },
  { id: 5048, word: "organism", meaning: "n. 生物体；有机体", unit: 5 },
  { id: 5049, word: "observatory", meaning: "n. 天文台；气象台", unit: 5 },
  { id: 5050, word: "breed", meaning: "v. 繁殖；饲养", unit: 5 },
  { id: 5051, word: "spread", meaning: "v. 传播；蔓延", unit: 5 },
  { id: 5052, word: "canyon", meaning: "n. 峡谷", unit: 5 },
  { id: 5053, word: "narrow", meaning: "adj. 狭窄的", unit: 5 },
  { id: 5054, word: "waterfall", meaning: "n. 瀑布", unit: 5 },
  { id: 5055, word: "thunder", meaning: "n. 雷；雷声", unit: 5 },
  { id: 5056, word: "channel", meaning: "n. 频道；渠道；海峡", unit: 5 },
  { id: 5057, word: "mammal", meaning: "n. 哺乳动物", unit: 5 },
  { id: 5058, word: "comet", meaning: "n. 彗星", unit: 5 },
  { id: 5059, word: "desert", meaning: "n. 沙漠", unit: 5 },
  { id: 5060, word: "climate", meaning: "n. 气候", unit: 5 },
  { id: 5061, word: "inside", meaning: "prep./adv. 在……里面", unit: 5 },
  { id: 5062, word: "cattle", meaning: "n. 牛；牲畜", unit: 5 },
  { id: 5063, word: "grain", meaning: "n. 谷物；颗粒", unit: 5 },
  { id: 5064, word: "sunflower", meaning: "n. 向日葵", unit: 5 },
  { id: 5065, word: "export", meaning: "v./n. 出口；输出", unit: 5 },
  { id: 5066, word: "branch", meaning: "n. 树枝；分支", unit: 5 },
  { id: 5067, word: "coastline", meaning: "n. 海岸线", unit: 5 },
  { id: 5068, word: "shark", meaning: "n. 鲨鱼", unit: 5 },
  { id: 5069, word: "tourism", meaning: "n. 旅游业", unit: 5 },
  { id: 5070, word: "pleasant", meaning: "adj. 令人愉快的", unit: 5 },
  { id: 5071, word: "reserve", meaning: "n. 自然保护区；储备", unit: 5 },
  { id: 5072, word: "energy", meaning: "n. 能源；精力", unit: 5 },
  { id: 5073, word: "wildlife", meaning: "n. 野生动物", unit: 5 },
  { id: 5074, word: "habitat", meaning: "n. 栖息地", unit: 5 },
  { id: 5075, word: "damage", meaning: "n./v. 损害；破坏", unit: 5 },
  { id: 5076, word: "hunt", meaning: "v. 打猎；捕猎", unit: 5 },
  { id: 5077, word: "survive", meaning: "v. 幸存；继续存在", unit: 5 },
  { id: 5078, word: "struggle", meaning: "v./n. 斗争；奋斗", unit: 5 },
  { id: 5079, word: "struggle for", meaning: "为……而斗争", unit: 5 },
  { id: 5080, word: "protect", meaning: "v. 保护", unit: 5 },
  { id: 5081, word: "protect...from", meaning: "保护……免受", unit: 5 },
  { id: 5082, word: "expert", meaning: "n. 专家", unit: 5 },
  { id: 5083, word: "release", meaning: "v. 释放；发布", unit: 5 },
  { id: 5084, word: "trap", meaning: "v. 困住 n. 陷阱", unit: 5 },
  { id: 5085, word: "aware", meaning: "adj. 知道的；意识到的", unit: 5 },
  { id: 5086, word: "be aware of", meaning: "意识到；知道", unit: 5 },
  { id: 5087, word: "symbol", meaning: "n. 象征", unit: 5 },
  { id: 5088, word: "population", meaning: "n. 人口；种群数量", unit: 5 },
  { id: 5089, word: "rate", meaning: "n. 速度；比率", unit: 5 },
  { id: 5090, word: "due to", meaning: "由于", unit: 5 },
  { id: 5091, word: "threat", meaning: "n. 威胁", unit: 5 },
  { id: 5092, word: "take action", meaning: "采取行动", unit: 5 },
  { id: 5093, word: "species", meaning: "n. 物种", unit: 5 },
  { id: 5094, word: "particular", meaning: "adj. 特定的；特别的", unit: 5 },
  { id: 5095, word: "ecology", meaning: "n. 生态", unit: 5 },
  { id: 5096, word: "ancient", meaning: "adj. 古老的；古代的", unit: 5 },
  { id: 5097, word: "ancestor", meaning: "n. 祖先；祖宗", unit: 5 },
  { id: 5098, word: "creature", meaning: "n. 生物", unit: 5 },
  { id: 5099, word: "endangered", meaning: "adj. 濒危的", unit: 5 },
  { id: 5100, word: "quantity", meaning: "n. 数量", unit: 5 },
  { id: 5101, word: "enormous", meaning: "adj. 巨大的；极大的", unit: 5 },
  { id: 5102, word: "decline", meaning: "v./n. 减少；下降", unit: 5 },
  { id: 5103, word: "disappear", meaning: "v. 消失；灭绝", unit: 5 },
  { id: 5104, word: "landscape", meaning: "n. 风景；地形", unit: 5 },
  { id: 5105, word: "result in", meaning: "导致", unit: 5 },
  { id: 5106, word: "reduce", meaning: "v. 减少", unit: 5 },

  // ==================== Unit 6: At one with nature (p.112-113) ====================
  { id: 6001, word: "wrap", meaning: "v. 包；裹", unit: 6 },
  { id: 6002, word: "frost", meaning: "n. 霜；霜冻", unit: 6 },
  { id: 6003, word: "threat", meaning: "n. 威胁", unit: 6 },
  { id: 6004, word: "therefore", meaning: "adv. 因此；所以", unit: 6 },
  { id: 6005, word: "steep", meaning: "adj. 陡峭的", unit: 6 },
  { id: 6006, word: "preserve", meaning: "v. 保护；保存", unit: 6 },
  { id: 6007, word: "harmony", meaning: "n. 和谐", unit: 6 },
  { id: 6008, word: "keep", meaning: "v. 保持；饲养", unit: 6 },
  { id: 6009, word: "horn", meaning: "n. 角；喇叭", unit: 6 },
  { id: 6010, word: "alarm", meaning: "n. 警报；惊恐", unit: 6 },
  { id: 6011, word: "spot", meaning: "v. 发现；认出", unit: 6 },
  { id: 6012, word: "material", meaning: "n. 材料；原料", unit: 6 },
  { id: 6013, word: "natural", meaning: "adj. 自然的；天然的", unit: 6 },
  { id: 6014, word: "disaster", meaning: "n. 灾难", unit: 6 },
  { id: 6015, word: "drought", meaning: "n. 旱灾；干旱", unit: 6 },
  { id: 6016, word: "flood", meaning: "n. 洪水；水灾", unit: 6 },
  { id: 6017, word: "hurricane", meaning: "n. 飓风", unit: 6 },
  { id: 6018, word: "tornado", meaning: "n. 龙卷风", unit: 6 },
  { id: 6019, word: "strike", meaning: "v. 侵袭；打击", unit: 6 },
  { id: 6020, word: "destroy", meaning: "v. 破坏；毁坏", unit: 6 },
  { id: 6021, word: "bury", meaning: "v. 埋葬；掩埋", unit: 6 },
  { id: 6022, word: "supply", meaning: "n./v. 供应；补给", unit: 6 },
  { id: 6023, word: "cut off", meaning: "切断", unit: 6 },
  { id: 6024, word: "ruin", meaning: "v./n. 毁坏；毁灭", unit: 6 },
  { id: 6025, word: "in ruins", meaning: "严重受损；破败不堪", unit: 6 },
  { id: 6026, word: "rescue", meaning: "v./n. 营救；救援", unit: 6 },
  { id: 6027, word: "shelter", meaning: "n. 避难所；庇护", unit: 6 },
  { id: 6028, word: "severe", meaning: "adj. 非常严重的；严峻的", unit: 6 },
  { id: 6029, word: "volunteer", meaning: "n./v. 志愿者；自愿做", unit: 6 },
  { id: 6030, word: "affect", meaning: "v. 影响", unit: 6 },
  { id: 6031, word: "recover", meaning: "v. 恢复；康复", unit: 6 },
  { id: 6032, word: "impact", meaning: "n. 影响；冲击", unit: 6 },
  { id: 6033, word: "have an impact on", meaning: "对……有影响", unit: 6 },
  { id: 6034, word: "phenomenon", meaning: "n. 现象", unit: 6 },
  { id: 6035, word: "atmosphere", meaning: "n. 大气层；气氛", unit: 6 },
  { id: 6036, word: "carbon dioxide", meaning: "二氧化碳", unit: 6 },
  { id: 6037, word: "emission", meaning: "n. 排放", unit: 6 },
  { id: 6038, word: "absorb", meaning: "v. 吸收", unit: 6 },
  { id: 6039, word: "in turn", meaning: "反过来", unit: 6 },
  { id: 6040, word: "balance", meaning: "n. 平衡", unit: 6 },
  { id: 6041, word: "temperature", meaning: "n. 温度", unit: 6 },
  { id: 6042, word: "pollution", meaning: "n. 污染", unit: 6 },
  { id: 6043, word: "solar", meaning: "adj. 太阳的；太阳能的", unit: 6 },
  { id: 6044, word: "consequence", meaning: "n. 结果；后果", unit: 6 },
  { id: 6045, word: "evidence", meaning: "n. 证据", unit: 6 },
  { id: 6046, word: "relevant", meaning: "adj. 有关的；切题的", unit: 6 },
  { id: 6047, word: "individual", meaning: "adj. 个人的 n. 个人", unit: 6 },
  { id: 6048, word: "recycle", meaning: "v. 回收利用", unit: 6 },
  { id: 6049, word: "contribute", meaning: "v. 贡献；捐献", unit: 6 },
  { id: 6050, word: "contribute to", meaning: "是……的原因之一；有助于", unit: 6 },
  { id: 6051, word: "promote", meaning: "v. 促进；推动", unit: 6 },
  { id: 6052, word: "efficiency", meaning: "n. 效率；效能", unit: 6 },
  { id: 6053, word: "renewable", meaning: "adj. 可再生的；可更新的", unit: 6 },
  { id: 6054, word: "resource", meaning: "n. 资源", unit: 6 },
  { id: 6055, word: "agriculture", meaning: "n. 农业", unit: 6 },
  { id: 6056, word: "original", meaning: "adj. 原来的；最初的", unit: 6 },
  { id: 6057, word: "transform", meaning: "v. 使改观；使变形", unit: 6 },
  { id: 6058, word: "sustainable", meaning: "adj. 可持续的", unit: 6 },
  { id: 6059, word: "guarantee", meaning: "v./n. 保证；担保", unit: 6 },
  { id: 6060, word: "circumstance", meaning: "n. 条件；环境；状况", unit: 6 },
  { id: 6061, word: "potential", meaning: "adj. 潜在的；可能的", unit: 6 },
  { id: 6062, word: "carbon", meaning: "n. 碳", unit: 6 },
  { id: 6063, word: "dioxide", meaning: "n. 二氧化物", unit: 6 },
  { id: 6064, word: "release", meaning: "v. 释放；发布", unit: 6 },
  { id: 6065, word: "trap", meaning: "v. 困住；使陷入", unit: 6 },
  { id: 6066, word: "take away", meaning: "带走；夺走", unit: 6 },
  { id: 6067, word: "result in", meaning: "导致", unit: 6 },
  { id: 6068, word: "put forward", meaning: "提出", unit: 6 },
  { id: 6069, word: "take action", meaning: "采取行动", unit: 6 },
  { id: 6070, word: "give off", meaning: "释放；放出", unit: 6 },
  { id: 6071, word: "deal with", meaning: "处理；应对", unit: 6 },
  { id: 6072, word: "be trapped in", meaning: "被困在", unit: 6 },
  { id: 6073, word: "cut down", meaning: "削减；砍倒", unit: 6 },
  { id: 6074, word: "have an effect on", meaning: "对……有影响", unit: 6 },
  { id: 6075, word: "as a result of", meaning: "由于……的结果", unit: 6 }
];
