// 外研社版高中英语必修第一册 词汇表

const UNITS = [
  { id: 1, name: "Unit 1 A new start" },
  { id: 2, name: "Unit 2 Exploring English" },
  { id: 3, name: "Unit 3 Family matters" },
  { id: 4, name: "Unit 4 Friends forever" },
  { id: 5, name: "Unit 5 Into the wild" },
  { id: 6, name: "Unit 6 At one with nature" }
];

const WORDS = [
  // ===== Unit 1: A new start =====
  { id: 1, word: "senior", meaning: "高级的；年长的", unit: 1 },
  { id: 2, word: "registration", meaning: "登记；注册", unit: 1 },
  { id: 3, word: "anxious", meaning: "焦虑的；不安的", unit: 1 },
  { id: 4, word: "annoyed", meaning: "恼怒的；生气的", unit: 1 },
  { id: 5, word: "frightened", meaning: "害怕的；受惊的", unit: 1 },
  { id: 6, word: "curious", meaning: "好奇的", unit: 1 },
  { id: 7, word: "concentrate", meaning: "集中（注意力）", unit: 1 },
  { id: 8, word: "experiment", meaning: "实验", unit: 1 },
  { id: 9, word: "explore", meaning: "探索；探究", unit: 1 },
  { id: 10, word: "confidence", meaning: "信心；自信", unit: 1 },
  { id: 11, word: "forward", meaning: "向前；前进", unit: 1 },
  { id: 12, word: "flash", meaning: "闪；闪光", unit: 1 },
  { id: 13, word: "organise", meaning: "组织；安排", unit: 1 },
  { id: 14, word: "goal", meaning: "目标；球门", unit: 1 },
  { id: 15, word: "impression", meaning: "印象", unit: 1 },
  { id: 16, word: "partner", meaning: "搭档；伙伴", unit: 1 },
  { id: 17, word: "improve", meaning: "改善；提高", unit: 1 },
  { id: 18, word: "challenge", meaning: "挑战", unit: 1 },
  { id: 19, word: "schedule", meaning: "日程表；时刻表", unit: 1 },
  { id: 20, word: "campus", meaning: "校园", unit: 1 },
  { id: 21, word: "lecture", meaning: "讲座；演讲", unit: 1 },
  { id: 22, word: "awkward", meaning: "令人尴尬的；笨拙的", unit: 1 },
  { id: 23, word: "description", meaning: "描写；描述", unit: 1 },
  { id: 24, word: "tradition", meaning: "传统", unit: 1 },
  { id: 25, word: "behavior", meaning: "行为；举止", unit: 1 },

  // ===== Unit 2: Exploring English =====
  { id: 26, word: "billion", meaning: "十亿", unit: 2 },
  { id: 27, word: "native", meaning: "本地的；土生土长的", unit: 2 },
  { id: 28, word: "attitude", meaning: "态度", unit: 2 },
  { id: 29, word: "system", meaning: "系统；体系", unit: 2 },
  { id: 30, word: "equal", meaning: "平等的；相等的", unit: 2 },
  { id: 31, word: "demand", meaning: "要求；需求", unit: 2 },
  { id: 32, word: "vocabulary", meaning: "词汇；词汇量", unit: 2 },
  { id: 33, word: "accent", meaning: "口音；腔调", unit: 2 },
  { id: 34, word: "actually", meaning: "实际上；事实上", unit: 2 },
  { id: 35, word: "expression", meaning: "表达；表情", unit: 2 },
  { id: 36, word: "command", meaning: "命令；掌握", unit: 2 },
  { id: 37, word: "request", meaning: "请求；要求", unit: 2 },
  { id: 38, word: "straight", meaning: "直的；直接地", unit: 2 },
  { id: 39, word: "block", meaning: "街区；大楼", unit: 2 },
  { id: 40, word: "apartment", meaning: "公寓", unit: 2 },
  { id: 41, word: "process", meaning: "过程；进程", unit: 2 },
  { id: 42, word: "consist", meaning: "由……组成", unit: 2 },
  { id: 43, word: "official", meaning: "官方的；正式的", unit: 2 },
  { id: 44, word: "voyage", meaning: "航行；航海", unit: 2 },
  { id: 45, word: "gradually", meaning: "逐渐地", unit: 2 },
  { id: 46, word: "identity", meaning: "身份；特征", unit: 2 },
  { id: 47, word: "phrase", meaning: "短语；词组", unit: 2 },
  { id: 48, word: "spelling", meaning: "拼写", unit: 2 },
  { id: 49, word: "distinguish", meaning: "区分；辨别", unit: 2 },
  { id: 50, word: "global", meaning: "全球的；全面的", unit: 2 },

  // ===== Unit 3: Family matters =====
  { id: 51, word: "teenager", meaning: "青少年", unit: 3 },
  { id: 52, word: "adult", meaning: "成年人", unit: 3 },
  { id: 53, word: "focus", meaning: "集中；聚焦", unit: 3 },
  { id: 54, word: "argument", meaning: "争论；论点", unit: 3 },
  { id: 55, word: "calm", meaning: "平静的；镇静的", unit: 3 },
  { id: 56, word: "ignore", meaning: "忽视；不理睬", unit: 3 },
  { id: 57, word: "gap", meaning: "差距；缺口", unit: 3 },
  { id: 58, word: "generation", meaning: "一代人；代", unit: 3 },
  { id: 59, word: "respect", meaning: "尊重；尊敬", unit: 3 },
  { id: 60, word: "trust", meaning: "信任", unit: 3 },
  { id: 61, word: "concern", meaning: "关心；担忧", unit: 3 },
  { id: 62, word: "communicate", meaning: "交流；沟通", unit: 3 },
  { id: 63, word: "support", meaning: "支持；支撑", unit: 3 },
  { id: 64, word: "grateful", meaning: "感激的；感谢的", unit: 3 },
  { id: 65, word: "suggest", meaning: "建议；暗示", unit: 3 },
  { id: 66, word: "suppose", meaning: "假设；认为", unit: 3 },
  { id: 67, word: "fault", meaning: "错误；过错", unit: 3 },
  { id: 68, word: "responsible", meaning: "有责任的；负责的", unit: 3 },
  { id: 69, word: "apologise", meaning: "道歉", unit: 3 },
  { id: 70, word: "character", meaning: "性格；角色；人物", unit: 3 },
  { id: 71, word: "selfish", meaning: "自私的", unit: 3 },
  { id: 72, word: "gentle", meaning: "温柔的；和善的", unit: 3 },
  { id: 73, word: "strict", meaning: "严格的", unit: 3 },
  { id: 74, word: "relationship", meaning: "关系", unit: 3 },
  { id: 75, word: "distance", meaning: "距离", unit: 3 },

  // ===== Unit 4: Friends forever =====
  { id: 76, word: "quality", meaning: "品质；质量", unit: 4 },
  { id: 77, word: "fond", meaning: "喜爱的", unit: 4 },
  { id: 78, word: "loyal", meaning: "忠诚的；忠实的", unit: 4 },
  { id: 79, word: "forever", meaning: "永远", unit: 4 },
  { id: 80, word: "adventure", meaning: "冒险；奇遇", unit: 4 },
  { id: 81, word: "prove", meaning: "证明；证实", unit: 4 },
  { id: 82, word: "inspire", meaning: "鼓舞；启发", unit: 4 },
  { id: 83, word: "virtue", meaning: "美德；优点", unit: 4 },
  { id: 84, word: "precious", meaning: "珍贵的；宝贵的", unit: 4 },
  { id: 85, word: "familiar", meaning: "熟悉的", unit: 4 },
  { id: 86, word: "bond", meaning: "纽带；联系", unit: 4 },
  { id: 87, word: "generous", meaning: "慷慨的；大方的", unit: 4 },
  { id: 88, word: "honour", meaning: "尊敬；荣誉", unit: 4 },
  { id: 89, word: "indeed", meaning: "的确；确实", unit: 4 },
  { id: 90, word: "sacrifice", meaning: "牺牲；献身", unit: 4 },
  { id: 91, word: "embrace", meaning: "拥抱；接受", unit: 4 },
  { id: 92, word: "outstanding", meaning: "杰出的；优秀的", unit: 4 },
  { id: 93, word: "extraordinary", meaning: "非凡的；卓越的", unit: 4 },
  { id: 94, word: "devote", meaning: "致力于；奉献", unit: 4 },
  { id: 95, word: "decade", meaning: "十年", unit: 4 },
  { id: 96, word: "cooperate", meaning: "合作；协作", unit: 4 },
  { id: 97, word: "bitter", meaning: "苦的；痛苦的", unit: 4 },
  { id: 98, word: "measure", meaning: "测量；措施", unit: 4 },
  { id: 99, word: "companion", meaning: "同伴；伙伴", unit: 4 },
  { id: 100, word: "resolve", meaning: "解决；决心", unit: 4 },

  // ===== Unit 5: Into the wild =====
  { id: 101, word: "wildlife", meaning: "野生动植物", unit: 5 },
  { id: 102, word: "habitat", meaning: "栖息地", unit: 5 },
  { id: 103, word: "species", meaning: "物种", unit: 5 },
  { id: 104, word: "endangered", meaning: "濒危的", unit: 5 },
  { id: 105, word: "reduce", meaning: "减少；降低", unit: 5 },
  { id: 106, word: "reserve", meaning: "保护区；储备", unit: 5 },
  { id: 107, word: "threat", meaning: "威胁；恐吓", unit: 5 },
  { id: 108, word: "authority", meaning: "权威；当局", unit: 5 },
  { id: 109, word: "expert", meaning: "专家", unit: 5 },
  { id: 110, word: "trap", meaning: "陷阱；困住", unit: 5 },
  { id: 111, word: "survive", meaning: "幸存；存活", unit: 5 },
  { id: 112, word: "aware", meaning: "意识到的", unit: 5 },
  { id: 113, word: "ecology", meaning: "生态学", unit: 5 },
  { id: 114, word: "particular", meaning: "特别的；特定的", unit: 5 },
  { id: 115, word: "ancient", meaning: "古代的；古老的", unit: 5 },
  { id: 116, word: "ancestor", meaning: "祖先；祖宗", unit: 5 },
  { id: 117, word: "creature", meaning: "生物；动物", unit: 5 },
  { id: 118, word: "pattern", meaning: "模式；图案", unit: 5 },
  { id: 119, word: "release", meaning: "释放；发布", unit: 5 },
  { id: 120, word: "preserve", meaning: "保护；保存", unit: 5 },
  { id: 121, word: "quantity", meaning: "数量", unit: 5 },
  { id: 122, word: "enormous", meaning: "巨大的；庞大的", unit: 5 },
  { id: 123, word: "decline", meaning: "下降；减少", unit: 5 },
  { id: 124, word: "disappear", meaning: "消失；不见", unit: 5 },
  { id: 125, word: "landscape", meaning: "风景；景色", unit: 5 },

  // ===== Unit 6: At one with nature =====
  { id: 126, word: "disaster", meaning: "灾难；灾害", unit: 6 },
  { id: 127, word: "drought", meaning: "干旱", unit: 6 },
  { id: 128, word: "flood", meaning: "洪水；淹没", unit: 6 },
  { id: 129, word: "hurricane", meaning: "飓风", unit: 6 },
  { id: 130, word: "tornado", meaning: "龙卷风", unit: 6 },
  { id: 131, word: "strike", meaning: "侵袭；罢工；打击", unit: 6 },
  { id: 132, word: "destroy", meaning: "破坏；毁灭", unit: 6 },
  { id: 133, word: "damage", meaning: "损害；损坏", unit: 6 },
  { id: 134, word: "rescue", meaning: "救援；营救", unit: 6 },
  { id: 135, word: "shelter", meaning: "避难所；庇护", unit: 6 },
  { id: 136, word: "ruin", meaning: "毁灭；废墟", unit: 6 },
  { id: 137, word: "affect", meaning: "影响", unit: 6 },
  { id: 138, word: "bury", meaning: "埋葬；掩埋", unit: 6 },
  { id: 139, word: "supply", meaning: "供给；补给", unit: 6 },
  { id: 140, word: "severe", meaning: "严重的；严厉的", unit: 6 },
  { id: 141, word: "struggle", meaning: "斗争；挣扎", unit: 6 },
  { id: 142, word: "volunteer", meaning: "志愿者", unit: 6 },
  { id: 143, word: "recover", meaning: "恢复；复原", unit: 6 },
  { id: 144, word: "impact", meaning: "影响；冲击", unit: 6 },
  { id: 145, word: "phenomenon", meaning: "现象", unit: 6 },
  { id: 146, word: "atmosphere", meaning: "大气层；气氛", unit: 6 },
  { id: 147, word: "carbon", meaning: "碳", unit: 6 },
  { id: 148, word: "emission", meaning: "排放", unit: 6 },
  { id: 149, word: "absorb", meaning: "吸收", unit: 6 },
  { id: 150, word: "pollution", meaning: "污染", unit: 6 },
  { id: 151, word: "temperature", meaning: "温度", unit: 6 },
  { id: 152, word: "balance", meaning: "平衡", unit: 6 },
  { id: 153, word: "solar", meaning: "太阳的；太阳能的", unit: 6 },
  { id: 154, word: "consequence", meaning: "结果；后果", unit: 6 },
  { id: 155, word: "evidence", meaning: "证据", unit: 6 },
  { id: 156, word: "relevant", meaning: "相关的；有意义的", unit: 6 },
  { id: 157, word: "individual", meaning: "个人的；个别的", unit: 6 },
  { id: 158, word: "recycle", meaning: "回收利用", unit: 6 },
  { id: 159, word: "contribute", meaning: "贡献；捐献", unit: 6 },
  { id: 160, word: "promote", meaning: "促进；推动", unit: 6 },
  { id: 161, word: "efficiency", meaning: "效率", unit: 6 },
  { id: 162, word: "renewable", meaning: "可再生的", unit: 6 },
  { id: 163, word: "resource", meaning: "资源", unit: 6 },
  { id: 164, word: "agriculture", meaning: "农业", unit: 6 },
  { id: 165, word: "original", meaning: "原来的；独创的", unit: 6 },
  { id: 166, word: "transform", meaning: "转变；改造", unit: 6 },
  { id: 167, word: "sustainable", meaning: "可持续的", unit: 6 },
  { id: 168, word: "guarantee", meaning: "保证；担保", unit: 6 },
  { id: 169, word: "circumstance", meaning: "环境；情况", unit: 6 },
  { id: 170, word: "potential", meaning: "潜在的；可能的", unit: 6 },

  // ===== Unit 1 词组/搭配 =====
  { id: 1001, word: "senior high school", meaning: "高中", unit: 1 },
  { id: 1002, word: "at last", meaning: "终于；最终", unit: 1 },
  { id: 1003, word: "look forward to", meaning: "期望；期待", unit: 1 },
  { id: 1004, word: "take notes", meaning: "记笔记", unit: 1 },
  { id: 1005, word: "make an impression", meaning: "留下印象", unit: 1 },
  { id: 1006, word: "what if", meaning: "要是……会怎么样", unit: 1 },
  { id: 1007, word: "on one's own", meaning: "独自地；独立地", unit: 1 },
  { id: 1008, word: "come true", meaning: "实现；成为现实", unit: 1 },
  { id: 1009, word: "make friends", meaning: "交朋友", unit: 1 },
  { id: 1010, word: "pay attention to", meaning: "注意；关注", unit: 1 },
  { id: 1011, word: "in other words", meaning: "换句话说", unit: 1 },
  { id: 1012, word: "have trouble with", meaning: "在……方面有困难", unit: 1 },

  // ===== Unit 2 词组/搭配 =====
  { id: 1013, word: "refer to", meaning: "指的是；参考", unit: 2 },
  { id: 1014, word: "play a role in", meaning: "在……中起作用", unit: 2 },
  { id: 1015, word: "even though", meaning: "即使；尽管", unit: 2 },
  { id: 1016, word: "from time to time", meaning: "不时；偶尔", unit: 2 },
  { id: 1017, word: "come about", meaning: "发生", unit: 2 },
  { id: 1018, word: "make use of", meaning: "利用", unit: 2 },
  { id: 1019, word: "such as", meaning: "例如", unit: 2 },
  { id: 1020, word: "because of", meaning: "因为；由于", unit: 2 },
  { id: 1021, word: "be based on", meaning: "以……为基础", unit: 2 },
  { id: 1022, word: "be known as", meaning: "被称为；作为……而闻名", unit: 2 },
  { id: 1023, word: "over time", meaning: "随着时间的推移", unit: 2 },
  { id: 1024, word: "a number of", meaning: "许多；若干", unit: 2 },

  // ===== Unit 3 词组/搭配 =====
  { id: 1025, word: "focus on", meaning: "集中于；关注", unit: 3 },
  { id: 1026, word: "be willing to", meaning: "愿意做某事", unit: 3 },
  { id: 1027, word: "calm down", meaning: "（使）平静下来", unit: 3 },
  { id: 1028, word: "instead of", meaning: "代替；而不是", unit: 3 },
  { id: 1029, word: "at the same time", meaning: "同时", unit: 3 },
  { id: 1030, word: "after all", meaning: "毕竟；终究", unit: 3 },
  { id: 1031, word: "agree with", meaning: "同意；赞同", unit: 3 },
  { id: 1032, word: "in one's view", meaning: "在某人看来", unit: 3 },
  { id: 1033, word: "generation gap", meaning: "代沟", unit: 3 },
  { id: 1034, word: "go through", meaning: "经历；经受", unit: 3 },
  { id: 1035, word: "be responsible for", meaning: "对……负责", unit: 3 },
  { id: 1036, word: "chat with", meaning: "与……聊天", unit: 3 },

  // ===== Unit 4 词组/搭配 =====
  { id: 1037, word: "be fond of", meaning: "喜欢；喜爱", unit: 4 },
  { id: 1038, word: "in need", meaning: "在困难中；在危难中", unit: 4 },
  { id: 1039, word: "count on", meaning: "依靠；指望", unit: 4 },
  { id: 1040, word: "make friends with", meaning: "与……交朋友", unit: 4 },
  { id: 1041, word: "from then on", meaning: "从那时起", unit: 4 },
  { id: 1042, word: "through thick and thin", meaning: "不畏艰险；同甘共苦", unit: 4 },
  { id: 1043, word: "be familiar with", meaning: "对……熟悉", unit: 4 },
  { id: 1044, word: "a couple of", meaning: "两三个；几个", unit: 4 },
  { id: 1045, word: "keep in touch with", meaning: "与……保持联系", unit: 4 },
  { id: 1046, word: "turn to", meaning: "向……求助", unit: 4 },
  { id: 1047, word: "devote oneself to", meaning: "致力于；献身于", unit: 4 },
  { id: 1048, word: "as a result", meaning: "结果；因此", unit: 4 },

  // ===== Unit 5 词组/搭配 =====
  { id: 1049, word: "die out", meaning: "灭绝；消失", unit: 5 },
  { id: 1050, word: "be aware of", meaning: "知道；意识到", unit: 5 },
  { id: 1051, word: "on earth", meaning: "究竟；到底", unit: 5 },
  { id: 1052, word: "in danger", meaning: "在危险中", unit: 5 },
  { id: 1053, word: "search for", meaning: "搜索；寻找", unit: 5 },
  { id: 1054, word: "come across", meaning: "偶然遇到", unit: 5 },
  { id: 1055, word: "carry out", meaning: "执行；实施", unit: 5 },
  { id: 1056, word: "set up", meaning: "建立；设立", unit: 5 },
  { id: 1057, word: "a variety of", meaning: "各种各样的", unit: 5 },
  { id: 1058, word: "adapt to", meaning: "适应", unit: 5 },
  { id: 1059, word: "due to", meaning: "由于；因为", unit: 5 },
  { id: 1060, word: "pay attention to", meaning: "注意；关注", unit: 5 },

  // ===== Unit 6 词组/搭配 =====
  { id: 1061, word: "take away", meaning: "带走；夺走", unit: 6 },
  { id: 1062, word: "result in", meaning: "导致", unit: 6 },
  { id: 1063, word: "put forward", meaning: "提出", unit: 6 },
  { id: 1064, word: "take action", meaning: "采取行动", unit: 6 },
  { id: 1065, word: "in turn", meaning: "依次；反过来", unit: 6 },
  { id: 1066, word: "give off", meaning: "释放；放出", unit: 6 },
  { id: 1067, word: "refer to", meaning: "提及；参考", unit: 6 },
  { id: 1068, word: "deal with", meaning: "处理；应对", unit: 6 },
  { id: 1069, word: "be trapped in", meaning: "被困在", unit: 6 },
  { id: 1070, word: "cut down", meaning: "削减；砍倒", unit: 6 },
  { id: 1071, word: "have an effect on", meaning: "对……有影响", unit: 6 },
  { id: 1072, word: "as a result of", meaning: "由于……的结果", unit: 6 }
];
